modules = [
  "ghostty",
  "fish",
  "shell",
  "meta",
  "projects",
  "python",
  "borgmatic",
  "devops",
  "git",
  "tmux",
  "nvim",
  "javascript",
  "asdf",
  "gnupg",
  "ai",

  # Only for my Home desktop
  { name = "linux", scopes = "desktop" },
  { name = "psi-notify", scopes = "desktop" },
  { name = "fontconfig", scopes = "desktop" },
  { name = "kde", scopes = "desktop" },
  { name = "zathura", scopes = "desktop" },
  { name = "golang", scopes = "desktop" },
  { name = "vlc", scopes = "desktop" },
  { name = "yazi", scopes = "desktop" },
  { name = "ruby", scopes = "desktop" },

  # Only for Work
  { name = "macos", scopes = "work" },
  { name = "work", scopes = "work" },
  { name = "ghostty-mac", scopes = "work" },

  # Disabled
  # { name = "gnome", scopes = "desktop" },
  # { name = "emacs" },
]
